########## Build Phase ##########
# Use node image as base (for the build phase)
# FROM node:18-alpine3.19 AS build
FROM node:18 AS build

# Set working directory (create the folders if not exists)
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package.*json ./

# Install app production dependencies only
RUN npm install

# Copy the rest of your application code to the working directory
COPY . .

RUN npm run build
RUN npm install --omit=dev

########## Execution Phase ##########
# Use node image as base (for the build phase)
FROM node:18-alpine3.19

WORKDIR /usr/src/app

COPY --from=build /usr/src/app/dist ./dist
COPY --from=build /usr/src/app/node_modules ./node_modules

EXPOSE 3333

CMD ["npm", "run", "start"]
