# Use node image
FROM node:18-alpine3.19

# Set working directory (create the folders if not exists)
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package.json yarn.lock .yarnrc.yml ./
COPY .yarn ./.yarn

# Install app dependencies
RUN yarn

# Copy the rest of your application code to the working directory
COPY . .

RUN yarn run build

EXPOSE 3333

CMD ["yarn", "run", "start"]
