# Use node image as base
FROM node:18-slim

# Set working directory (create the folders if not exists)
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package.*json ./

# Install app dependencies
RUN npm install

# Copy the rest of your application code to the working directory
COPY . .

RUN npm run build

EXPOSE 3333

CMD ["npm", "run", "start"]
